apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceEnricherConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-

    kafka.streams.config {
      application.id = structured-traces-enrichment-job
      metrics.recording.level = "{{ .Values.traceEnricherConfig.kafka.streams.config.metricsRecordingLevel }}"
      num.stream.threads = "{{ .Values.traceEnricherConfig.kafka.streams.config.numStreamThreads }}"
      producer.compression.type = gzip
      topology.optimization = all
      bootstrap.servers = "{{ .Values.traceEnricherConfig.kafka.streams.config.bootstrapServers }}"
      auto.offset.reset = "latest"
      auto.commit.interval.ms = 5000
    }

    schema.registry.config {
      schema.registry.url = "{{ .Values.traceEnricherConfig.schema.registry.config.schemaRegistryUrl }}"
      specific.avro.reader = true
    }

    enricher {
      DefaultServiceEntityEnricher {
        entity.service.config = {
          host = entity-service
          port = 50061
        }
      }

      BackendEntityEnricher {
        entity.service.config = {
          host = entity-service
          port = 50061
        }
      }

      EndpointEnricher {
        entity.service.config = {
          host = entity-service
          port = 50061
        }
      }
    }
